# Generated by Django 5.1.15 on 2026-08-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
        ("properties", "0003_project_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdocument",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kb_documents",
                to="properties.project",
            ),
        ),
    ]
