# Generated by Django 5.1.15 on 2026-08-04 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('properties', '0002_alter_project_options_project_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('segment_type', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATED', 'Automated'), ('AI_MATCHED', 'AI Matched'), ('CSV_IMPORT', 'CSV Import')], default='MANUAL', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('customer_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_segments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH_NOTIFICATION', 'Push Notification'), ('SALES_SCRIPT', 'Sales Script'), ('VOICE_SCRIPT', 'Voice Call Script'), ('FACEBOOK_POST', 'Facebook Post'), ('INSTAGRAM_CAPTION', 'Instagram Caption')], max_length=30)),
                ('whatsapp_template', models.TextField(blank=True, default='')),
                ('email_template', models.TextField(blank=True, default='')),
                ('sms_template', models.TextField(blank=True, default='')),
                ('push_template', models.TextField(blank=True, default='')),
                ('sales_script_template', models.TextField(blank=True, default='')),
                ('voice_script_template', models.TextField(blank=True, default='')),
                ('facebook_template', models.TextField(blank=True, default='')),
                ('instagram_template', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='en', max_length=20)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(choices=[('PROJECT_LAUNCH', 'Project Launch'), ('PRICE_UPDATE', 'Price Update'), ('FESTIVAL_OFFER', 'Festival Offer'), ('INVENTORY_UPDATE', 'Inventory Update'), ('GENERAL_ANNOUNCEMENT', 'General Announcement'), ('CUSTOM', 'Custom')], default='GENERAL_ANNOUNCEMENT', max_length=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Scheduled', 'Scheduled'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('ai_prompt', models.TextField(blank=True, default='')),
                ('message_versions', models.JSONField(blank=True, default=dict)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=50)),
                ('total_reach', models.IntegerField(default=0)),
                ('delivered', models.IntegerField(default=0)),
                ('opened', models.IntegerField(default=0)),
                ('clicked', models.IntegerField(default=0)),
                ('replied', models.IntegerField(default=0)),
                ('interested', models.IntegerField(default=0)),
                ('site_visits', models.IntegerField(default=0)),
                ('calls_booked', models.IntegerField(default=0)),
                ('meetings', models.IntegerField(default=0)),
                ('bookings', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='broadcast.audiencesegment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_campaigns', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_campaigns', to='properties.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_stats', models.JSONField(blank=True, default=dict)),
                ('hourly_stats', models.JSONField(blank=True, default=dict)),
                ('city_stats', models.JSONField(blank=True, default=dict)),
                ('builder_stats', models.JSONField(blank=True, default=dict)),
                ('campaign_stats', models.JSONField(blank=True, default=dict)),
                ('ai_recommendations', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='broadcast.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Campaign Analytics',
            },
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='INFO', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='broadcast.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('channel', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked'), ('FAILED', 'Failed'), ('REPLIED', 'Replied')], default='PENDING', max_length=20)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('reply_content', models.TextField(blank=True, default='')),
                ('failed_reason', models.TextField(blank=True, default='')),
                ('booking', models.BooleanField(default=False)),
                ('booking_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='broadcast.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('contacts', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_contact_lists', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='contact_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='broadcast.contactlist'),
        ),
    ]
