# Generated by Django 5.1.15 on 2026-08-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='click_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='conversion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='campaign',
            name='open_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reach',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='selected_customer_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_type',
            field=models.CharField(blank=True, default='AI_MATCHED', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_sent',
            field=models.IntegerField(default=0),
        ),
    ]
