# Generated by Django 5.1.15 on 2026-07-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("MANAGER", "Manager"),
                    ("AGENT", "Agent"),
                ],
                default="AGENT",
                max_length=20,
            ),
        ),
    ]
