# Generated by Django 5.1.15 on 2026-07-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverification",
            name="token",
        ),
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="token",
        ),
        migrations.AddField(
            model_name="emailverification",
            name="otp_code",
            field=models.CharField(default="000000", max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="otp_code",
            field=models.CharField(default="000000", max_length=6),
            preserve_default=False,
        ),
    ]
