# Generated by Django 5.1.15 on 2026-07-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
