# Generated by Django 5.1.15 on 2026-07-08 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_emailverification_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("otp_code", models.CharField(max_length=255)),
                ("otp_expires_at", models.DateTimeField()),
                ("verification_attempts", models.IntegerField(default=0)),
                ("resend_count", models.IntegerField(default=0)),
                ("last_resend_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="verification_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="otp_code",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="EmailVerification",
        ),
    ]
