# Generated by Django 5.1.15 on 2026-08-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_project_options_project_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
