# Generated by Django 5.1.15 on 2026-07-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("lead_created", "Lead Created"),
                            ("deal_stage_changed", "Deal Stage Changed"),
                            ("task_completed", "Task Completed"),
                        ],
                        default="lead_created",
                        max_length=50,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_notification", "Send Notification"),
                            ("create_task", "Create Task"),
                            ("enrich_lead", "Enrich Lead via AI"),
                        ],
                        default="send_notification",
                        max_length=50,
                    ),
                ),
                ("action_params", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
