# Generated by Django 5.1.15 on 2026-07-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADING", "Uploading"),
                    ("EXTRACTING", "Extracting"),
                    ("CHUNKING", "Chunking"),
                    ("EMBEDDING", "Embedding"),
                    ("READY", "Ready"),
                    ("FAILED", "Failed"),
                ],
                default="UPLOADING",
                max_length=20,
            ),
        ),
    ]
