# Generated by Django 5.1.15 on 2026-08-04 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='', max_length=20)),
                ('occupation', models.CharField(blank=True, default='', max_length=150)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/photos/')),
                ('lead_status', models.CharField(choices=[('HOT', 'Hot Lead'), ('WARM', 'Warm Lead'), ('COLD', 'Cold Lead'), ('NEW', 'New'), ('CONTACTED', 'Contacted'), ('VISITED', 'Visited'), ('NEGOTIATION', 'In Negotiation'), ('BOOKED', 'Booked'), ('CLOSED', 'Closed'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('WHATSAPP', 'WhatsApp'), ('FACEBOOK_ADS', 'Facebook Ads'), ('INSTAGRAM', 'Instagram'), ('GOOGLE_ADS', 'Google Ads'), ('REFERRAL', 'Referral'), ('BROKER', 'Broker'), ('WALK_IN', 'Walk-in'), ('SALES_EXECUTIVE', 'Sales Executive'), ('CSV_IMPORT', 'CSV Import'), ('EXISTING_CUSTOMER', 'Existing Customer'), ('OTHER', 'Other')], default='', max_length=30)),
                ('source_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('CUSTOMER_CREATED', 'Customer Created'), ('BUDGET_UPDATED', 'Budget Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('ASSIGNED', 'Customer Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('ARCHIVED', 'Customer Archived'), ('RESTORED', 'Customer Restored'), ('NOTE_ADDED', 'Note Added'), ('CALL_LOGGED', 'Call Logged'), ('MEETING', 'Meeting'), ('EMAIL', 'Email Sent')], max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.CharField(blank=True, default='', max_length=150)),
                ('address', models.TextField(blank=True, default='')),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='#6366f1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_categories', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PAN', 'PAN'), ('AADHAR', 'Aadhar'), ('PASSPORT', 'Passport'), ('LOAN_PAPERS', 'Loan Papers'), ('AGREEMENT', 'Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_customer_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_lists', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('INVESTMENT', 'Investment'), ('SELF_USE', 'Self Use'), ('RENTAL', 'Rental')], default='', max_length=20)),
                ('property_type', models.CharField(blank=True, choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('PLOT', 'Plot'), ('OFFICE', 'Office'), ('SHOP', 'Shop'), ('COMMERCIAL', 'Commercial')], default='', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=list)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_city', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_area', models.CharField(blank=True, default='', max_length=150)),
                ('preferred_builder', models.CharField(blank=True, default='', max_length=255)),
                ('loan_required', models.BooleanField(default=False)),
                ('parking_required', models.BooleanField(default=False)),
                ('possession_preference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('WHATSAPP', 'WhatsApp'), ('FACEBOOK_ADS', 'Facebook Ads'), ('INSTAGRAM', 'Instagram'), ('GOOGLE_ADS', 'Google Ads'), ('REFERRAL', 'Referral'), ('BROKER', 'Broker'), ('WALK_IN', 'Walk-in'), ('SALES_EXECUTIVE', 'Sales Executive'), ('CSV_IMPORT', 'CSV Import'), ('EXISTING_CUSTOMER', 'Existing Customer'), ('OTHER', 'Other')], default='', max_length=30)),
                ('added_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('employee_id_display', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('referral_name', models.CharField(blank=True, default='', max_length=255)),
                ('referral_phone', models.CharField(blank=True, default='', max_length=50)),
                ('relationship', models.CharField(blank=True, default='', max_length=150)),
                ('broker_name', models.CharField(blank=True, default='', max_length=255)),
                ('broker_company', models.CharField(blank=True, default='', max_length=255)),
                ('broker_phone', models.CharField(blank=True, default='', max_length=50)),
                ('commission', models.CharField(blank=True, default='', max_length=50)),
                ('campaign_name', models.CharField(blank=True, default='', max_length=255)),
                ('landing_page', models.URLField(blank=True, default='')),
                ('utm_source', models.CharField(blank=True, default='', max_length=150)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=150)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=150)),
                ('import_file', models.CharField(blank=True, default='', max_length=255)),
                ('import_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sources', to='employees.employee')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_detail', to='customers.customer')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_customers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerListCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_lists', to='customers.customer')),
                ('customer_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_customers', to='customers.customerlist')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='organizations.organization')),
            ],
            options={
                'unique_together': {('customer_list', 'customer')},
            },
        ),
    ]
