# Generated by Django 5.1.15 on 2026-07-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcastcampaign",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
