# Generated by Django 5.1.15 on 2026-08-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_broadcastcampaign_content'),
        ('properties', '0003_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastcampaign',
            name='click_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='conversion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='open_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_broadcast_campaigns', to='properties.project'),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='selected_customer_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='target_type',
            field=models.CharField(choices=[('AI_MATCHED', 'AI Customer Matched'), ('SELECTED_CUSTOMERS', 'Selected Existing Customers'), ('CSV_UPLOAD', 'CSV Customer Upload'), ('ALL_CUSTOMERS', 'All System Customers')], default='AI_MATCHED', max_length=30),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='total_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='broadcastcampaign',
            name='reach',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
